name: Go Users API Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  testing:
    name: Testing API
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - name: Test
        run: go test -v ./...
