name: Go Users API Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Testing API
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.2

      - name: Test
        run: go test -v ./...
        env:
          ENVIRONMENT: "testing"

      - name: Build
        run: go build

      - name: Set up Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLYIO_TOKEN }}
